### ISSUE TITLE
Off the grid checkins as private posts

### ISSUE THREAD

**Issue by sebsel** [aaronpk/OwnYourSwarm#32]
At the moment, off the grid checkins (does anyone use them?) are treaded like any other checkin, resulting in a public checkin on your own site and a private checkin on Swarm.

I suppose this one needs some more research for how to make a private post via Micropub.
Possible option would be `visibility=private`. This is how Wordpress calls it now (see https://indieweb.org/post_status)

Few questions to be answered:
- do people use "off the grid" checkins?
- do people support private posts?
- how to send the private-ness through Micropub?

**Comment by aaronpk** [comment]
There's a mention of `visibility=private` in the extensions page: https://indieweb.org/Micropub-extensions#Visibility

Currently Quill has implemented `post-status=draft` and I use it all the time with my site.

I think public/private is a good start for private posts, especially since there is precedent for that with things like Swarm. I do want to be able to support the more complex limited audience posts the way Facebook does, so we might need to brainstorm that a little further as well. Or, call public/private good enough for a first pass at implementing it.

**Comment by dshanske** [comment]
I vote for visibility. This will shortly be supported in WordPress... waiting on merge
